#!/bin/bash
# vendored-session.sh — orchestrator for vendored session hooks.
# Generated by madp --install-hooks. Do not edit manually.
set -euo pipefail

MODE=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --start) MODE="start"; shift ;;
        --resume) MODE="resume"; shift ;;
        *) shift ;;
    esac
done

if [ -z "$MODE" ]; then
    echo "Usage: vendored-session.sh --start|--resume" >&2
    exit 1
fi

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
VENDORED_INSTALL="$PROJECT_DIR/.vendored/install"

if [ ! -f "$VENDORED_INSTALL" ]; then
    echo "Warning: .vendored/install not found, skipping hook orchestration" >&2
    exit 0
fi

# ── Post-install safety net ──────────────────────────────────────────────────
# Check version stamps and re-run stale post-install hooks before session hooks.
MANIFESTS_DIR="$PROJECT_DIR/.vendored/manifests"
VENDORS=$(python3 "$VENDORED_INSTALL" --list 2>/dev/null) || true

if [ -n "$VENDORS" ]; then
    while IFS= read -r vendor_name; do
        [ -z "$vendor_name" ] && continue
        version_file="$MANIFESTS_DIR/$vendor_name.version"
        stamp_file="$MANIFESTS_DIR/$vendor_name.post-installed"
        post_install_hook="$PROJECT_DIR/.vendored/pkg/$vendor_name/hooks/post-install.sh"

        # Skip if no version file (not installed)
        [ ! -f "$version_file" ] && continue
        # Skip if no post-install hook
        [ ! -f "$post_install_hook" ] && continue

        # Compare stamps: run post-install if stamp is missing or differs
        if [ ! -f "$stamp_file" ] || [ "$(cat "$version_file")" != "$(cat "$stamp_file")" ]; then
            VENDOR_NAME="$vendor_name" \
            VENDOR_PKG_DIR="$PROJECT_DIR/.vendored/pkg/$vendor_name" \
            PROJECT_DIR="$PROJECT_DIR" \
            bash "$post_install_hook"
            # Update stamp on success
            cp "$version_file" "$stamp_file"
        fi
    done <<< "$VENDORS"
fi

# ── Session hooks ────────────────────────────────────────────────────────────
# Discover and run session hooks in dependency order.
HOOK_PATHS=$(python3 "$VENDORED_INSTALL" --hooks "$MODE" 2>/dev/null) || true

if [ -z "$HOOK_PATHS" ]; then
    exit 0
fi

# Run each vendor's hook with env vars
while IFS= read -r hook_path; do
    [ -z "$hook_path" ] && continue
    # Extract vendor name from path: .vendored/pkg/<vendor>/hooks/<hook>
    vendor_dir=$(dirname "$(dirname "$hook_path")")
    vendor_name=$(basename "$vendor_dir")

    VENDOR_NAME="$vendor_name" \
    VENDOR_PKG_DIR="$vendor_dir" \
    PROJECT_DIR="$PROJECT_DIR" \
    bash "$hook_path"
done <<< "$HOOK_PATHS"
