#!/bin/bash
# Auto-generated by git-vendored — do not edit manually.
# Dispatches to vendor hooks in dependency order.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_DIR
export CLAUDE_PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PROJECT_DIR}"

# Parse mode: --start (default) or --resume
MODE="start"
case "${1:-}" in
  --start)  MODE="start" ;;
  --resume) MODE="resume" ;;
esac

# Post-install safety net: run post-install.sh if version stamp is stale
run_post_install_if_needed() {
  local vendor="$1"
  local hook="$2"
  local version_file="$PROJECT_DIR/.vendored/manifests/$vendor.version"
  local stamp_file="$PROJECT_DIR/.vendored/manifests/$vendor.post-installed"

  [ -f "$hook" ] || return 0

  local current_version=""
  [ -f "$version_file" ] && current_version="$(cat "$version_file" | tr -d '\n')"
  local stamp_version=""
  [ -f "$stamp_file" ] && stamp_version="$(cat "$stamp_file" | tr -d '\n')"

  if [ "$current_version" != "$stamp_version" ]; then
    echo "Running post-install for $vendor..."
    if bash "$hook"; then
      echo "$current_version" > "$stamp_file"
    else
      echo "Warning: post-install.sh failed for $vendor" >&2
    fi
  fi
}

  # ── pearls ──
  VENDOR_NAME="pearls"
  VENDOR_PKG_DIR="$PROJECT_DIR/.vendored/pkg/pearls"
  export VENDOR_NAME VENDOR_PKG_DIR
  run_post_install_if_needed "pearls" "$VENDOR_PKG_DIR/hooks/post-install.sh"
  if [ "$MODE" = "start" ]; then
    [ -f "$VENDOR_PKG_DIR/hooks/session-start.sh" ] && bash "$VENDOR_PKG_DIR/hooks/session-start.sh"
  elif [ "$MODE" = "resume" ]; then
    [ -f "$VENDOR_PKG_DIR/hooks/session-resume.sh" ] && bash "$VENDOR_PKG_DIR/hooks/session-resume.sh"
  fi
